// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bovhjexmffzdvrfpobig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvdmhqZXhtZmZ6ZHZyZnBvYmlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4OTUyNzAsImV4cCI6MjA4ODQ3MTI3MH0.BEpGNUrAS4rtdkeE3iRfpI4SGJSADRSZO8O7N7MNOI8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});